id: A99EE8848
base_file: f9A54.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:37:06.934337
  last_modified_at: 2022-06-11 13:37:06.934344
