id: A99EE8848
base_file: fB3E6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:37:06.939728
  last_modified_at: 2022-06-11 13:37:06.939735
